In [8]:
import pandas as pd
import numpy as np
import os

In [ ]:
data_path = "../data/raw/"

In [9]:

customers = pd.read_csv(
    data_path + "olist_customers_dataset.csv"
)

orders = pd.read_csv(
    data_path + "olist_orders_dataset.csv"
)

order_items = pd.read_csv(
    data_path + "olist_order_items_dataset.csv"
)

order_payments = pd.read_csv(
    data_path + "olist_order_payments_dataset.csv"
)

order_reviews = pd.read_csv(
    data_path + "olist_order_reviews_dataset.csv"
)

products = pd.read_csv(
    data_path + "olist_products_dataset.csv"
)

sellers = pd.read_csv(
    data_path + "olist_sellers_dataset.csv"
)

product_category_translation = pd.read_csv(
    data_path + "product_category_name_translation.csv"
)

geolocation = pd.read_csv(
    data_path + "olist_geolocation_dataset.csv"
)

In [10]:

tables = {
    "CUSTOMERS": customers,
    "ORDERS": orders,
    "ORDER_ITEMS": order_items,
    "ORDER_PAYMENTS": order_payments,
    "ORDER_REVIEWS": order_reviews,
    "PRODUCTS": products,
    "SELLERS": sellers,
    "PRODUCT_CATEGORY_TRANSLATION": product_category_translation,
    "GEOLOCATION": geolocation
}

In [11]:
cleaned_tables = {
    table_name: df.copy()
    for table_name, df in tables.items()
}

In [12]:

customers_clean = cleaned_tables["CUSTOMERS"]
orders_clean = cleaned_tables["ORDERS"]
order_items_clean = cleaned_tables["ORDER_ITEMS"]
order_payments_clean = cleaned_tables["ORDER_PAYMENTS"]
order_reviews_clean = cleaned_tables["ORDER_REVIEWS"]
products_clean = cleaned_tables["PRODUCTS"]
sellers_clean = cleaned_tables["SELLERS"]
product_category_translation_clean = cleaned_tables["PRODUCT_CATEGORY_TRANSLATION"]
geolocation_clean = cleaned_tables["GEOLOCATION"]

In [13]:
tables

{'CUSTOMERS':                             customer_id                customer_unique_id  \
 0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
 1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
 2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
 3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
 4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
 ...                                 ...                               ...
 99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
 99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
 99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
 99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
 99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

        customer_zip_code_prefix          customer_city customer_state
 0                         14409                 franca             SP
 1                          9790  sao bernardo do campo             SP
 2                          1151              sao paulo             SP
 3                          8775        mogi das cruzes             SP
 4                         13056               campinas             SP
 ...                         ...                    ...            ...
 99436                      3937              sao paulo             SP
 99437                      6764        taboao da serra             SP
 99438                     60115              fortaleza             CE
 99439                     92120                 canoas             RS
 99440                      6703                  cotia             SP

 [99441 rows x 5 columns],
 'ORDERS':                                order_id                       customer_id  \
 0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
 1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
 2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
 3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
 4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
 ...                                 ...                               ...
 99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
 99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
 99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
 99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
 99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp    order_approved_at  \
 0        delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
 1        delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
 2        delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
 3        delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
 4        delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
 ...            ...                      ...                  ...
 99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
 99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
 99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
 99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
 99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

       order_delivered_carrier_date order_delivered_customer_date  \
 0              2017-10-04 19:55:00           2017-10-10 21:25:13
 1              2018-07-26 14:31:00           2018-08-07 15:27:45
 2              2018-08-08 13:50:00           2018-08-17 18:06:29
 3              2017-11-22 13:39:59           2017-12-02 00:28:42
 4              2018-02-14 19:46:34           2018-02-16 18:17:02
 ...                            ...                           ...
 99436          2017-03-10 11:18:03           2017-03-17 15:08:01
 99437          2018-02-07 23:22:42           2018-02-28 17:37:56
 99438          2017-08-28 20:52:26           2017-09-21 11:24:17
 99439          2018-01-12 15:35:03           2018-01-25 23:32:54
 99440          2018-03-09 22:11:59           2018-03-16 13:08:30

       order_estimated_delivery_date
 0               2017-10-18 00:00:00
 1               2018-08-13 00:00:00
 2               2018-09-04 00:00:00
 3               2017-12-15 00:00:00
 4               2018-02-26 00:00:00
 ...                             ...
 99436           2017-03-28 00:00:00
 99437           2018-03-02 00:00:00
 99438           2017-09-27 00:00:00
 99439           2018-02-15 00:00:00
 99440           2018-04-03 00:00:00

 [99441 rows x 8 columns],
 'ORDER_ITEMS':                                 order_id  order_item_id  \
 0       00010242fe8c5a6d1ba2dd792cb16214              1
 1       00018f77f2f0320c557190d7a144bdd3              1
 2       000229ec398224ef6ca0657da4fc703e              1
 3       00024acbcdf0a6daa1e931b038114c75              1
 4       00042b26cf59d7ce69dfabb4e55b4fd9              1
 ...                                  ...            ...
 112645  fffc94f6ce00a00581880bf54a75a037              1
 112646  fffcd46ef2263f404302a634eb57f7eb              1
 112647  fffce4705a9662cd70adb13d4a31832d              1
 112648  fffe18544ffabc95dfada21779c9644f              1
 112649  fffe41c64501cc87c801fd61db3f6244              1

                               product_id                         seller_id  \
 0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
 1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
 2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
 3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
 4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
 ...                                  ...                               ...
 112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
 112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
 112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
 112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
 112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

         shipping_limit_date   price  freight_value
 0       2017-09-19 09:45:35   58.90          13.29
 1       2017-05-03 11:05:13  239.90          19.93
 2       2018-01-18 14:48:30  199.00          17.87
 3       2018-08-15 10:10:18   12.99          12.79
 4       2017-02-13 13:57:51  199.90          18.14
 ...                     ...     ...            ...
 112645  2018-05-02 04:11:01  299.99          43.41
 112646  2018-07-20 04:31:48  350.00          36.53
 112647  2017-10-30 17:14:25   99.90          16.95
 112648  2017-08-21 00:04:32   55.99           8.72
 112649  2018-06-12 17:10:13   43.00          12.79

 [112650 rows x 7 columns],
 'ORDER_PAYMENTS':                                 order_id  payment_sequential payment_type  \
 0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
 1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
 2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
 3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
 4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
 ...                                  ...                 ...          ...
 103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
 103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
 103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
 103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
 103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

         payment_installments  payment_value
 0                          8          99.33
 1                          1          24.39
 2                          1          65.71
 3                          8         107.78
 4                          2         128.45
 ...                      ...            ...
 103881                     1         363.31
 103882                     2          96.80
 103883                     1          47.77
 103884                     5         369.54
 103885                     1         191.58

 [103886 rows x 5 columns],
 'ORDER_REVIEWS':                               review_id                          order_id  \
 0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
 1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
 2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
 3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
 4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
 ...                                 ...                               ...
 99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
 99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
 99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
 99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
 99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

        review_score review_comment_title  \
 0                 4                  NaN
 1                 5                  NaN
 2                 5                  NaN
 3                 5                  NaN
 4                 5                  NaN
 ...             ...                  ...
 99219             5                  NaN
 99220             5                  NaN
 99221             5                  NaN
 99222             4                  NaN
 99223             1                  NaN

                                   review_comment_message review_creation_date  \
 0                                                    NaN  2018-01-18 00:00:00
 1                                                    NaN  2018-03-10 00:00:00
 2                                                    NaN  2018-02-17 00:00:00
 3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
 4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00
 ...                                                  ...                  ...
 99219                                                NaN  2018-07-07 00:00:00
 99220                                                NaN  2017-12-09 00:00:00
 99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
 99222                                                NaN  2018-07-01 00:00:00
 99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

       review_answer_timestamp
 0         2018-01-18 21:46:59
 1         2018-03-11 03:05:13
 2         2018-02-18 14:36:24
 3         2017-04-21 22:02:06
 4         2018-03-02 10:26:53
 ...                       ...
 99219     2018-07-14 17:18:30
 99220     2017-12-11 20:06:42
 99221     2018-03-23 09:10:43
 99222     2018-07-02 12:59:13
 99223     2017-07-03 21:01:49

 [99224 rows x 7 columns],
 'PRODUCTS':                              product_id              product_category_name  \
 0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
 1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
 2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
 3      cef67bcfe19066a932b7673e239eb23d                              bebes
 4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
 ...                                 ...                                ...
 32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
 32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
 32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
 32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
 32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

        product_name_lenght  product_description_lenght  product_photos_qty  \
 0                     40.0                       287.0                 1.0
 1                     44.0                       276.0                 1.0
 2                     46.0                       250.0                 1.0
 3                     27.0                       261.0                 1.0
 4                     37.0                       402.0                 4.0
 ...                    ...                         ...                 ...
 32946                 45.0                        67.0                 2.0
 32947                 41.0                       971.0                 1.0
 32948                 50.0                       799.0                 1.0
 32949                 60.0                       156.0                 2.0
 32950                 58.0                       309.0                 1.0

        product_weight_g  product_length_cm  product_height_cm  \
 0                 225.0               16.0               10.0
 1                1000.0               30.0               18.0
 2                 154.0               18.0                9.0
 3                 371.0               26.0                4.0
 4                 625.0               20.0               17.0
 ...                 ...                ...                ...
 32946           12300.0               40.0               40.0
 32947            1700.0               16.0               19.0
 32948            1400.0               27.0                7.0
 32949             700.0               31.0               13.0
 32950            2083.0               12.0                2.0

        product_width_cm
 0                  14.0
 1                  20.0
 2                  15.0
 3                  26.0
 4                  13.0
 ...                 ...
 32946              40.0
 32947              16.0
 32948              27.0
 32949              20.0
 32950               7.0

 [32951 rows x 9 columns],
 'SELLERS':                              seller_id  seller_zip_code_prefix  \
 0     3442f8959a84dea7ee197c632cb2df15                   13023
 1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
 2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
 3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
 4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
 ...                                ...                     ...
 3090  98dddbc4601dd4443ca174359b237166                   87111
 3091  f8201cab383e484733266d1906e2fdfa                   88137
 3092  74871d19219c7d518d0090283e03c137                    4650
 3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
 3094  9e25199f6ef7e7c347120ff175652c3b                   12051

             seller_city seller_state
 0              campinas           SP
 1            mogi guacu           SP
 2        rio de janeiro           RJ
 3             sao paulo           SP
 4     braganca paulista           SP
 ...                 ...          ...
 3090            sarandi           PR
 3091            palhoca           SC
 3092          sao paulo           SP
 3093            pelotas           RS
 3094            taubate           SP

 [3095 rows x 4 columns],
 'PRODUCT_CATEGORY_TRANSLATION':             product_category_name product_category_name_english
 0                    beleza_saude                 health_beauty
 1          informatica_acessorios         computers_accessories
 2                      automotivo                          auto
 3                 cama_mesa_banho                bed_bath_table
 4                moveis_decoracao               furniture_decor
 ..                            ...                           ...
 66                         flores                       flowers
 67             artes_e_artesanato         arts_and_craftmanship
 68                fraldas_higiene           diapers_and_hygiene
 69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
 70             seguros_e_servicos         security_and_services

 [71 rows x 2 columns],
 'GEOLOCATION':          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
 0                               1037       -23.545621       -46.639292
 1                               1046       -23.546081       -46.644820
 2                               1046       -23.546129       -46.642951
 3                               1041       -23.544392       -46.639499
 4                               1035       -23.541578       -46.641607
 ...                              ...              ...              ...
 1000158                        99950       -28.068639       -52.010705
 1000159                        99900       -27.877125       -52.224882
 1000160                        99950       -28.071855       -52.014716
 1000161                        99980       -28.388932       -51.846871
 1000162                        99950       -28.070104       -52.018658

         geolocation_city geolocation_state
 0              sao paulo                SP
 1              sao paulo                SP
 2              sao paulo                SP
 3              sao paulo                SP
 4              sao paulo                SP
 ...                  ...               ...
 1000158         tapejara                RS
 1000159   getulio vargas                RS
 1000160         tapejara                RS
 1000161  david canabarro                RS
 1000162         tapejara                RS

 [1000163 rows x 5 columns]}

In [14]:
missing_before = []

for table_name, df in cleaned_tables.items():
    for column in df.columns:
        missing_count = df[column].isna().sum()

        if missing_count > 0:
            missing_before.append({
                "Table": table_name,
                "Column": column,
                "Missing_Count": missing_count,
                "Missing_Percentage": round(
                    (missing_count / len(df)) * 100, 2
                )
            })

missing_before_df = pd.DataFrame(missing_before)

missing_before_df

,Table,Column,Missing_Count,Missing_Percentage
0,ORDERS,order_approved_at,160,0.16
1,ORDERS,order_delivered_carrier_date,1783,1.79
2,ORDERS,order_delivered_customer_date,2965,2.98
3,ORDER_REVIEWS,review_comment_title,87656,88.34
4,ORDER_REVIEWS,review_comment_message,58247,58.70
5,PRODUCTS,product_category_name,610,1.85
6,PRODUCTS,product_name_lenght,610,1.85
7,PRODUCTS,product_description_lenght,610,1.85
8,PRODUCTS,product_photos_qty,610,1.85
9,PRODUCTS,product_weight_g,2,0.01
10,PRODUCTS,product_length_cm,2,0.01
11,PRODUCTS,product_height_cm,2,0.01
12,PRODUCTS,product_width_cm,2,0.01

In [15]:
orders_clean[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].isna().sum()

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

In [16]:
order_reviews_clean["review_comment_title"] = (
    order_reviews_clean["review_comment_title"]
    .fillna("")
)

order_reviews_clean["review_comment_message"] = (
    order_reviews_clean["review_comment_message"]
    .fillna("")
)
print(
    "Missing review titles:",
    order_reviews_clean["review_comment_title"].isna().sum()
)

print(
    "Missing review messages:",
    order_reviews_clean["review_comment_message"].isna().sum()
)

Missing review titles: 0
Missing review messages: 0

In [17]:
products_clean["product_category_name"] = (
    products_clean["product_category_name"]
    .fillna("unknown")
)

In [18]:
products_clean["product_category_name"].isna().sum()

np.int64(0)

In [19]:
product_numeric_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

products_clean[product_numeric_columns].isna().sum()

product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [20]:
order_date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in order_date_columns:
    orders_clean[column] = pd.to_datetime(
        orders_clean[column],
        errors="coerce"
    )
orders_clean[order_date_columns].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [21]:
order_items_clean["shipping_limit_date"] = pd.to_datetime(
    order_items_clean["shipping_limit_date"],
    errors="coerce"
)

In [23]:
order_reviews_clean["review_creation_date"] = pd.to_datetime(
    order_reviews_clean["review_creation_date"],
    errors="coerce"
)
order_reviews_clean["review_creation_date"].dtype

dtype('<M8[us]')

In [25]:
numeric_columns = {
    "ORDER_ITEMS": [
        "order_item_id",
        "price",
        "freight_value"
    ],
    "ORDER_PAYMENTS": [
        "payment_sequential",
        "payment_installments",
        "payment_value"
    ],
    "ORDER_REVIEWS": [
        "review_score"
    ],
    "PRODUCTS": [
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
}

for column in numeric_columns["ORDER_ITEMS"]:
    order_items_clean[column] = pd.to_numeric(
        order_items_clean[column],
        errors="coerce"
    )

for column in numeric_columns["ORDER_PAYMENTS"]:
    order_payments_clean[column] = pd.to_numeric(
        order_payments_clean[column],
        errors="coerce"
    )

order_reviews_clean["review_score"] = pd.to_numeric(
    order_reviews_clean["review_score"],
    errors="coerce"
)

for column in numeric_columns["PRODUCTS"]:
    products_clean[column] = pd.to_numeric(
        products_clean[column],
        errors="coerce"
    )

In [26]:
print("ORDER_ITEMS")
print(order_items_clean[numeric_columns["ORDER_ITEMS"]].dtypes)

print("\nORDER_PAYMENTS")
print(order_payments_clean[numeric_columns["ORDER_PAYMENTS"]].dtypes)

print("\nORDER_REVIEWS")
print(order_reviews_clean[["review_score"]].dtypes)

print("\nPRODUCTS")
print(products_clean[numeric_columns["PRODUCTS"]].dtypes)

ORDER_ITEMS
order_item_id      int64
price            float64
freight_value    float64
dtype: object

ORDER_PAYMENTS
payment_sequential        int64
payment_installments      int64
payment_value           float64
dtype: object

ORDER_REVIEWS
review_score    int64
dtype: object

PRODUCTS
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [27]:
orders_clean["order_status"] = (
    orders_clean["order_status"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [28]:
orders_clean["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64[pyarrow]

In [29]:
valid_order_status = {
    "delivered",
    "shipped",
    "canceled",
    "unavailable",
    "invoiced",
    "processing",
    "created",
    "approved"
}

invalid_order_status = orders_clean[
    ~orders_clean["order_status"].isin(valid_order_status)
]

print("Invalid order status records:", len(invalid_order_status))

Invalid order status records: 0

In [31]:
order_payments_clean["payment_type"] = (
    order_payments_clean["payment_type"]
    .astype("string")
    .str.strip()
    .str.lower()
)
order_payments_clean["payment_type"].value_counts(dropna=False)

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64[pyarrow]

In [32]:
customers_clean["customer_city"] = (
    customers_clean["customer_city"]
    .astype("string")
    .str.strip()
)

customers_clean["customer_state"] = (
    customers_clean["customer_state"]
    .astype("string")
    .str.strip()
    .str.upper()
)

In [33]:
sellers_clean["seller_city"] = (
    sellers_clean["seller_city"]
    .astype("string")
    .str.strip()
)

sellers_clean["seller_state"] = (
    sellers_clean["seller_state"]
    .astype("string")
    .str.strip()
    .str.upper()
)

In [34]:
products_clean["product_category_name"] = (
    products_clean["product_category_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [35]:
product_category_translation_clean[
    "product_category_name"
] = (
    product_category_translation_clean["product_category_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

product_category_translation_clean[
    "product_category_name_english"
] = (
    product_category_translation_clean[
        "product_category_name_english"
    ]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [36]:
invalid_review_scores = order_reviews_clean[
    ~order_reviews_clean["review_score"].isin([1, 2, 3, 4, 5])
]

print("Invalid review scores:", len(invalid_review_scores))

Invalid review scores: 0

In [37]:
invalid_freight = order_items_clean[
    order_items_clean["freight_value"] < 0
]

print("Invalid freight records:", len(invalid_freight))

Invalid freight records: 0

In [38]:
invalid_installments = order_payments_clean[
    order_payments_clean["payment_installments"] <= 0
]

print("Invalid payment installment records:", len(invalid_installments))

Invalid payment installment records: 2

In [39]:
cleaned_tables = {
    "CUSTOMERS": customers_clean,
    "ORDERS": orders_clean,
    "ORDER_ITEMS": order_items_clean,
    "ORDER_PAYMENTS": order_payments_clean,
    "ORDER_REVIEWS": order_reviews_clean,
    "PRODUCTS": products_clean,
    "SELLERS": sellers_clean,
    "PRODUCT_CATEGORY_TRANSLATION": product_category_translation_clean,
    "GEOLOCATION": geolocation_clean
}

In [40]:
geo_before = len(geolocation_clean)

geolocation_clean = (
    geolocation_clean
    .drop_duplicates()
    .reset_index(drop=True)
)

geo_after = len(geolocation_clean)

print("GEOLOCATION rows before:", geo_before)
print("GEOLOCATION rows after:", geo_after)
print("Exact duplicate rows removed:", geo_before - geo_after)

GEOLOCATION rows before: 1000163
GEOLOCATION rows after: 738332
Exact duplicate rows removed: 261831

In [41]:
cleaned_tables["GEOLOCATION"] = geolocation_clean

In [42]:
order_item_duplicates = order_items_clean.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

print(
    "Duplicate ORDER_ITEMS business keys:",
    order_item_duplicates
)

Duplicate ORDER_ITEMS business keys: 0

In [44]:
review_id_duplicates = order_reviews_clean[
    order_reviews_clean["review_id"].duplicated(keep=False)
].sort_values("review_id")

review_id_duplicates.head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,,,2017-09-21,2017-09-26 03:27:47
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,,,2017-09-21,2017-09-26 03:27:47
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,,,2018-03-02,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,,,2018-03-02,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,,,2017-07-29,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,,,2017-07-29,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,,,2017-07-27,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,,,2017-07-27,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,,,2017-05-14,2017-05-15 02:17:38
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1,,,2017-05-14,2017-05-15 02:17:38
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5,,,2017-02-09,2017-02-14 15:58:44
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5,,,2017-02-09,2017-02-14 15:58:44

In [45]:
review_business_duplicates = order_reviews_clean.duplicated(
    subset=["review_id", "order_id"]
).sum()

print(
    "Duplicate REVIEW_ID + ORDER_ID combinations:",
    review_business_duplicates
)

Duplicate REVIEW_ID + ORDER_ID combinations: 0

In [46]:
geo_key_counts = (
    geolocation_clean["geolocation_zip_code_prefix"]
    .value_counts()
)

geo_key_counts.head(10)

geolocation_zip_code_prefix
38400    779
35500    751
11680    727
11740    678
36400    627
38408    621
39400    620
35162    611
37200    596
35900    589
Name: count, dtype: int64

In [47]:
row_count_summary = []

for table_name in tables:
    original_rows = len(tables[table_name])
    cleaned_rows = len(cleaned_tables[table_name])

    row_count_summary.append({
        "Table": table_name,
        "Original_Rows": original_rows,
        "Cleaned_Rows": cleaned_rows,
        "Rows_Removed": original_rows - cleaned_rows
    })

row_count_df = pd.DataFrame(row_count_summary)

row_count_df

                          Table  Original_Rows  Cleaned_Rows  Rows_Removed
0                     CUSTOMERS          99441         99441             0
1                        ORDERS          99441         99441             0
2                   ORDER_ITEMS         112650        112650             0
3                ORDER_PAYMENTS         103886        103886             0
4                 ORDER_REVIEWS          99224         99224             0
5                      PRODUCTS          32951         32951             0
6                       SELLERS           3095          3095             0
7  PRODUCT_CATEGORY_TRANSLATION             71            71             0
8                   GEOLOCATION        1000163        738332        261831

In [48]:
final_missing = []

for table_name, df in cleaned_tables.items():

    for column in df.columns:

        missing_count = df[column].isna().sum()

        if missing_count > 0:

            final_missing.append({
                "Table": table_name,
                "Column": column,
                "Missing_Count": missing_count,
                "Missing_Percentage": round(
                    (missing_count / len(df)) * 100,
                    2
                )
            })

final_missing_df = pd.DataFrame(final_missing)

final_missing_df

      Table                         Column  Missing_Count  Missing_Percentage
0    ORDERS              order_approved_at            160                0.16
1    ORDERS   order_delivered_carrier_date           1783                1.79
2    ORDERS  order_delivered_customer_date           2965                2.98
3  PRODUCTS            product_name_lenght            610                1.85
4  PRODUCTS     product_description_lenght            610                1.85
5  PRODUCTS             product_photos_qty            610                1.85
6  PRODUCTS               product_weight_g              2                0.01
7  PRODUCTS              product_length_cm              2                0.01
8  PRODUCTS              product_height_cm              2                0.01
9  PRODUCTS               product_width_cm              2                0.01

In [49]:
for table_name, df in cleaned_tables.items():

    print("=" * 70)
    print(table_name)
    print("=" * 70)

    print(df.dtypes)
    print()

======================================================================
CUSTOMERS
======================================================================
customer_id                    str
customer_unique_id             str
customer_zip_code_prefix     int64
customer_city               string
customer_state              string
dtype: object

======================================================================
ORDERS
======================================================================
order_id                                    str
customer_id                                 str
order_status                             string
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

======================================================================
ORDER_ITEMS
======================================================================
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

======================================================================
ORDER_PAYMENTS
======================================================================
order_id                    str
payment_sequential        int64
payment_type             string
payment_installments      int64
payment_value           float64
dtype: object

======================================================================
ORDER_REVIEWS
======================================================================
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp               str
dtype: object

======================================================================
PRODUCTS
======================================================================
product_id                        str
product_category_name          string
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

======================================================================
SELLERS
======================================================================
seller_id                    str
seller_zip_code_prefix     int64
seller_city               string
seller_state              string
dtype: object

======================================================================
PRODUCT_CATEGORY_TRANSLATION
======================================================================
product_category_name            string
product_category_name_english    string
dtype: object

======================================================================
GEOLOCATION
======================================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [50]:
final_quality_summary = []

for table_name, df in cleaned_tables.items():

    final_quality_summary.append({
        "Table": table_name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Total_Missing_Values": int(df.isna().sum().sum()),
        "Duplicate_Rows": int(df.duplicated().sum())
    })

final_quality_df = pd.DataFrame(final_quality_summary)

final_quality_df

,Table,Rows,Columns,Total_Missing_Values,Duplicate_Rows
0,CUSTOMERS,99441,5,0,0
1,ORDERS,99441,8,4908,0
2,ORDER_ITEMS,112650,7,0,0
3,ORDER_PAYMENTS,103886,5,0,0
4,ORDER_REVIEWS,99224,7,0,0
5,PRODUCTS,32951,9,1838,0
6,SELLERS,3095,4,0,0
7,PRODUCT_CATEGORY_TRANSLATION,71,2,0,0
8,GEOLOCATION,738332,5,0,0

In [51]:
cleaned_path = "../data/cleaned/"

os.makedirs(cleaned_path, exist_ok=True)

In [52]:
output_files = {
    "CUSTOMERS": "customers_cleaned.csv",
    "ORDERS": "orders_cleaned.csv",
    "ORDER_ITEMS": "order_items_cleaned.csv",
    "ORDER_PAYMENTS": "order_payments_cleaned.csv",
    "ORDER_REVIEWS": "order_reviews_cleaned.csv",
    "PRODUCTS": "products_cleaned.csv",
    "SELLERS": "sellers_cleaned.csv",
    "PRODUCT_CATEGORY_TRANSLATION": "product_category_translation_cleaned.csv",
    "GEOLOCATION": "geolocation_cleaned.csv"
}

for table_name, df in cleaned_tables.items():

    file_path = os.path.join(
        cleaned_path,
        output_files[table_name]
    )

    df.to_csv(file_path, index=False)

    print(f"Saved: {file_path}")

Saved: ../data/cleaned/customers_cleaned.csv
Saved: ../data/cleaned/orders_cleaned.csv
Saved: ../data/cleaned/order_items_cleaned.csv
Saved: ../data/cleaned/order_payments_cleaned.csv
Saved: ../data/cleaned/order_reviews_cleaned.csv
Saved: ../data/cleaned/products_cleaned.csv
Saved: ../data/cleaned/sellers_cleaned.csv
Saved: ../data/cleaned/product_category_translation_cleaned.csv
Saved: ../data/cleaned/geolocation_cleaned.csv